#!/usr/bin/env python3
"""下载 Mozilla CA bundle 并生成嵌入头文件 src/fetch/cacert_embedded.hpp。

生成的头文件被 gitignore（构建产物，与 vcpkg 同模式）。
来源：curl.se/ca/cacert.pem（Mozilla CA bundle），另有 raw.githubusercontent 备源。
"""
import pathlib
import sys
import urllib.request

URLS = [
    "https://curl.se/ca/cacert.pem",
    "https://raw.githubusercontent.com/curl/curl-ca-bundle/master/ca-bundle.crt",
]
OUT = pathlib.Path(__file__).resolve().parents[2] / "quickjs-runtime" / "src" / "fetch" / "cacert_embedded.hpp"


def fetch() -> bytes:
    last: Exception | None = None
    for url in URLS:
        try:
            with urllib.request.urlopen(url, timeout=60) as resp:
                data = resp.read()
            if b"BEGIN CERTIFICATE" in data:
                return data
            last = RuntimeError(f"{url}: 内容不是 PEM 证书包")
        except Exception as exc:  # noqa: BLE001 —— 下载失败换备源
            last = exc
    raise SystemExit(f"全部下载源失败: {last}")


def main() -> int:
    # 幂等：产物已存在则跳过下载（网络不可达时复用已有产物，configure 可离线跑通）
    if OUT.exists() and OUT.stat().st_size > 0:
        print(f"SKIP: {OUT} 已存在（如需刷新请先删除后重跑）")
        return 0
    pem = fetch()
    text = pem.decode("utf-8", "replace").strip()
    if ")QJS_CERT" in text:
        raise SystemExit("PEM 内容包含与 raw string 分隔符冲突的序列 )QJS_CERT")
    out = f"""// Auto-generated. Do not edit. Generated by scripts/bootstrap_cacert.py.
// Source: Mozilla CA bundle (curl.se/ca/cacert.pem), embedded for TLS verification.
#pragma once
#include <string_view>
namespace fetch {{
inline constexpr std::string_view embedded_cacert_pem = R"QJS_CERT(
{text}
)QJS_CERT";
}} // namespace fetch
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(out, encoding="utf-8")
    print(f"OK: {OUT} ({len(pem) // 1024} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
