#!/usr/bin/env python3
"""把 JS 文件嵌入为 C++ 字符串常量头文件（polyfill / shim 嵌入用）。

用法:
    python scripts/embed_js.py <output.hpp> <input.js> [input2.js ...] [--namespace NS]

每个输入文件生成一个 `inline constexpr std::string_view <文件名stem>_js`，
内容为 JS 源码原文（raw string literal，不做任何转义/压缩）。
变量名由文件名 stem 转 snake_case 得到；多个输入可合并进同一个 hpp。

示例:
    python scripts/embed_js.py include/qjsbind/web/wpt_shim_embedded.hpp tests/wpt_shim.js
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DELIM = "QJS_JS"  # raw string 分隔符：R"QJS_JS(...)QJS_JS"


def var_name(path: Path) -> str:
    stem = re.sub(r"[^0-9A-Za-z]+", "_", path.stem).strip("_").lower()
    if stem and stem[0].isdigit():
        stem = "_" + stem
    return f"{stem}_js"


def main() -> int:
    parser = argparse.ArgumentParser(description="把 JS 文件嵌入为 C++ 字符串头文件")
    parser.add_argument("output", type=Path, help="输出 .hpp 路径")
    parser.add_argument("inputs", type=Path, nargs="+", help="输入 .js 文件（可多个）")
    parser.add_argument("--namespace", default="qjsbind::web",
                        help="生成代码的命名空间（默认 qjsbind::web）")
    args = parser.parse_args()

    chunks: list[str] = []
    seen: dict[str, Path] = {}
    for js in args.inputs:
        text = js.read_text(encoding="utf-8")
        if f"){DELIM}\"" in text:
            print(f"错误: {js} 内容包含与 raw string 分隔符冲突的序列 ){DELIM}\"",
                  file=sys.stderr)
            return 1
        name = var_name(js)
        if name in seen:
            print(f"错误: 变量名冲突: {name}（{seen[name]} 与 {js}）", file=sys.stderr)
            return 1
        seen[name] = js
        chunks.append(f"// 来源: {js.name}\n"
                      f"inline constexpr std::string_view {name} = R\"{DELIM}(\n"
                      f"{text}"
                      f"\n){DELIM}\";\n")

    ns_open = "\n".join(f"namespace {ns} {{" for ns in args.namespace.split("::"))
    ns_close = "\n".join(f"}} // namespace {ns}"
                         for ns in reversed(args.namespace.split("::")))
    out = (
        "// Auto-generated. Do not edit. Generated by scripts/embed_js.py.\n"
        f"// Sources: {', '.join(p.name for p in args.inputs)}\n"
        "#pragma once\n"
        "#include <string_view>\n\n"
        f"{ns_open}\n\n"
        + "\n".join(chunks)
        + f"\n{ns_close}\n"
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(out, encoding="utf-8")
    print(f"OK: {args.output}（{len(args.inputs)} 个 JS 文件）")
    return 0


if __name__ == "__main__":
    sys.exit(main())
