// GENERATED by dart_cpp_bridge codegen — do not edit.
// ignore_for_file: unused_element

import 'dart:ffi';

import 'package:dart_cpp_bridge/dart_cpp_bridge.dart';
import 'package:ffi/ffi.dart';

const _kAssetId = 'package:zephyr/src/native_gen/dcb_bindings.dart';

@Native<InitDartApiC>(assetId: _kAssetId, symbol: 'dcb_init_dart_api')
external int _dcbInitDartApi(Pointer<Void> data);

@Native<SessionOpenC>(assetId: _kAssetId, symbol: 'dcb_session_open')
external int _dcbSessionOpen(int replyNativePort);

@Native<SessionCloseC>(assetId: _kAssetId, symbol: 'dcb_session_close')
external void _dcbSessionClose(int sessionId);

@Native<ShutdownC>(assetId: _kAssetId, symbol: 'dcb_shutdown')
external void _dcbShutdown();

@Native<InvokeSyncC>(assetId: _kAssetId, symbol: 'dcb_invoke_sync')
external Pointer<Uint8> _dcbInvokeSync(
  int sessionId,
  Pointer<Uint8> req,
  int reqLen,
  Pointer<IntPtr> outLen,
  Pointer<Pointer<Utf8>> errorOut,
);

@Native<InvokeAsyncC>(assetId: _kAssetId, symbol: 'dcb_invoke_async')
external void _dcbInvokeAsync(int sessionId, Pointer<Uint8> req, int reqLen);

@Native<StreamCloseC>(assetId: _kAssetId, symbol: 'dcb_stream_close')
external void _dcbStreamClose(int sessionId, int streamId);

@Native<DartFnReplyC>(assetId: _kAssetId, symbol: 'dcb_dart_fn_reply')
external void _dcbDartFnReply(
  int sessionId,
  int replyId,
  int ok,
  Pointer<Uint8> payload,
  int payloadLen,
  Pointer<Utf8> errorMsg,
);

@Native<FreeC>(assetId: _kAssetId, symbol: 'dcb_free')
external void _dcbFree(Pointer<Void> p);

@Native<SetVerboseErrorsC>(assetId: _kAssetId, symbol: 'dcb_set_verbose_errors')
external void _dcbSetVerboseErrors(int enabled);

@Native<SetPoolThreadsC>(assetId: _kAssetId, symbol: 'dcb_set_pool_threads')
external void _dcbSetPoolThreads(int n);

@Native<Pointer<Void> Function()>(
  assetId: _kAssetId,
  symbol: 'dcb_session_finalizer_ptr',
)
external Pointer<Void> _dcbSessionFinalizerPtr();

@Native<Pointer<Void> Function()>(
  assetId: _kAssetId,
  symbol: 'dcb_drop_object_ptr',
)
external Pointer<Void> _dcbDropObjectPtr();

/// Creates the [NativeBindings] for this package's native library.
NativeBindings createDcbBindings() {
  return NativeBindings(
    initDartApi: _dcbInitDartApi,
    sessionOpen: _dcbSessionOpen,
    sessionClose: _dcbSessionClose,
    sessionFinalizer: _dcbSessionFinalizerPtr().cast<FinalizerFn>(),
    shutdown: _dcbShutdown,
    invokeSync: _dcbInvokeSync,
    invokeAsync: _dcbInvokeAsync,
    streamClose: _dcbStreamClose,
    dartFnReply: _dcbDartFnReply,
    free: _dcbFree,
    setVerboseErrors: _dcbSetVerboseErrors,
    setPoolThreads: _dcbSetPoolThreads,
    dropObject: _dcbDropObjectPtr().cast<FinalizerFn>(),
  );
}
