// GENERATED by dart_cpp_bridge codegen — do not edit.
// ignore_for_file: unused_element, unused_import

import 'dart:async';
import 'dart:typed_data';

import 'package:dart_cpp_bridge/dart_cpp_bridge.dart';

/// Wire-level API singleton. Access via [BridgeApiImpl.instance].
final class BridgeApiImpl {
  BridgeApiImpl._(this.bridge);

  final DartCppBridge bridge;

  // ── Singleton ──
  static BridgeApiImpl? _instance;
  static BridgeApiImpl get instance {
    final i = _instance;
    if (i == null) throw StateError('DcbLib.init() must be called first');
    return i;
  }

  static void initSingleton(DartCppBridge bridge) =>
      _instance = BridgeApiImpl._(bridge);
  static void disposeSingleton() => _instance = null;

  static const int heavyComputeId = 117270329;
  static const int addId = 1130012286;
  static const int fetchGreetingId = 1278131711;

  Future<String> heavyCompute(int input) async {
    final payload = ByteWriter();
    payload.i32(input);
    final payloadBytes = payload.takeBytes();
    final bytes = await bridge.invokeAsyncMethod(heavyComputeId, payloadBytes);
    return ByteReader(bytes).str();
  }

  int add(int a, int b) {
    final payload = ByteWriter();
    payload.i32(a);
    payload.i32(b);
    final payloadBytes = payload.takeBytes();
    final bytes = bridge.invokeSyncMethod(addId, payloadBytes);
    return ByteReader(bytes).i32();
  }

  Future<String> fetchGreeting(String name) async {
    final payload = ByteWriter();
    payload.str(name);
    final payloadBytes = payload.takeBytes();
    final bytes = await bridge.invokeAsyncMethod(fetchGreetingId, payloadBytes);
    return ByteReader(bytes).str();
  }
}
