// GENERATED by dart_cpp_bridge codegen — do not edit.
// ignore_for_file: unused_element, unused_import

import 'dart:ffi';
import 'dart:async';
import 'dart:typed_data';

import 'package:dart_cpp_bridge/dart_cpp_bridge.dart';

import 'api/bridge_api.dart';

void _writeDataClass_WindDownloadProgress(ByteWriter w, WindDownloadProgress v) {
  w.i64(v.received);
  w.i64(v.total);
}

WindDownloadProgress _readDataClass_WindDownloadProgress(ByteReader _r) {
  return WindDownloadProgress(
    received: _r.i64(),
    total: _r.i64(),
  );
}
void _writeDataClass_WindFetchInit(ByteWriter w, WindFetchInit v) {
  w.str(v.method);
  w.u32(v.headers.length);
  v.headers.forEach((final _k, final _v) {
    w.str(_k);
    w.str(_v);
  });
  w.u8vec(v.body);
  w.i64(v.timeoutMs);
  if (v.followRedirects == null) { w.u8(0); } else { w.u8(1);
    w.u8(v.followRedirects! ? 1 : 0);
  }
}

WindFetchInit _readDataClass_WindFetchInit(ByteReader _r) {
  return WindFetchInit(
    method: _r.str(),
    headers: (() { final _n = _r.u32(); final _result = <String, String>{}; for (var _i = 0; _i < _n; _i++) { _result[_r.str()] = _r.str(); } return _result; })(),
    body: _r.u8vec(),
    timeoutMs: _r.i64(),
    followRedirects: ((_r.u8() != 0) ? _r.u8() != 0 : null),
  );
}
void _writeDataClass_WindFetchResponse(ByteWriter w, WindFetchResponse v) {
  w.i32(v.status);
  w.str(v.statusText);
  w.u32(v.headers.length);
  v.headers.forEach((final _k, final _v) {
    w.str(_k);
    w.str(_v);
  });
  w.u8vec(v.body);
  w.str(v.url);
  w.u8(v.redirected ? 1 : 0);
}

WindFetchResponse _readDataClass_WindFetchResponse(ByteReader _r) {
  return WindFetchResponse(
    status: _r.i32(),
    statusText: _r.str(),
    headers: (() { final _n = _r.u32(); final _result = <String, String>{}; for (var _i = 0; _i < _n; _i++) { _result[_r.str()] = _r.str(); } return _result; })(),
    body: _r.u8vec(),
    url: _r.str(),
    redirected: _r.u8() != 0,
  );
}

/// Wire-level API singleton. Access via [BridgeApiImpl.instance].
final class BridgeApiImpl {
  BridgeApiImpl._(this.bridge);

  final DartCppBridge bridge;

  // ── Singleton ──
  static BridgeApiImpl? _instance;
  static BridgeApiImpl get instance {
    final i = _instance;
    if (i == null) throw StateError('DcbLib.init() must be called first');
    return i;
  }
  static void initSingleton(DartCppBridge bridge) => _instance = BridgeApiImpl._(bridge);
  static void disposeSingleton() => _instance = null;

  static const int heavyComputeId = 117270329;
  static const int qjsDebugSnapshotId = 129382005;
  static const int qjsClearBundleId = 229742803;
  static const int qjsSetHttpProxyId = 332377940;
  static const int qjsBuildRuntimeId = 381890690;
  static const int qjsSetSocks5ProxyId = 614503869;
  static const int antiObfuscationPictureId = 673703455;
  static const int qjsIsInitializedId = 915368852;
  static const int qjsDropRuntimeId = 1096426791;
  static const int addId = 1130012286;
  static const int qjsTaskCallId = 1159358141;
  static const int fetchGreetingId = 1278131711;
  static const int qjsSetTlsVerifyEnabledId = 1461330420;
  static const int qjsReplaceBundleId = 1679656109;
  static const int qjsCurrentBundleId = 1714687961;
  static const int windHttpClientNewWithDefaultHeadersId = 33985225;
  static const int windHttpClientFetchId = 596115912;
  static const int windHttpClientDownloadId = 1023045398;
  static const int windHttpClientAliveCountId = 2058390274;

  Future<String> heavyCompute(int input) async {
    final _payload = ByteWriter();
    _payload.i32(input);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(heavyComputeId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<String> qjsDebugSnapshot(String runtimeName) async {
    final _payload = ByteWriter();
    _payload.str(runtimeName);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(qjsDebugSnapshotId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<bool> qjsClearBundle(String runtimeName) async {
    final _payload = ByteWriter();
    _payload.str(runtimeName);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(qjsClearBundleId, _payloadBytes);
    return ByteReader(_bytes).u8() != 0;
  }

  void qjsSetHttpProxy(String proxy) {
    final _payload = ByteWriter();
    _payload.str(proxy);
    final _payloadBytes = _payload.takeBytes();
    bridge.invokeSyncMethod(qjsSetHttpProxyId, _payloadBytes);
  }

  Future<void> qjsBuildRuntime(String runtimeName, String bundleName, String bundleJs) async {
    final _payload = ByteWriter();
    _payload.str(runtimeName);
    _payload.str(bundleName);
    _payload.str(bundleJs);
    final _payloadBytes = _payload.takeBytes();
    await bridge.invokeAsyncMethod(qjsBuildRuntimeId, _payloadBytes);
  }

  void qjsSetSocks5Proxy(String proxy) {
    final _payload = ByteWriter();
    _payload.str(proxy);
    final _payloadBytes = _payload.takeBytes();
    bridge.invokeSyncMethod(qjsSetSocks5ProxyId, _payloadBytes);
  }

  Future<void> antiObfuscationPicture(Pointer<Uint8> imgData, int imgDataLen, int chapterId, String url, String fileName) async {
    final _payload = ByteWriter();
    _payload.u64(imgData.address);
    _payload.i32(imgDataLen);
    _payload.i32(chapterId);
    _payload.str(url);
    _payload.str(fileName);
    final _payloadBytes = _payload.takeBytes();
    await bridge.invokeAsyncMethod(antiObfuscationPictureId, _payloadBytes);
  }

  Future<bool> qjsIsInitialized(String runtimeName) async {
    final _payload = ByteWriter();
    _payload.str(runtimeName);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(qjsIsInitializedId, _payloadBytes);
    return ByteReader(_bytes).u8() != 0;
  }

  Future<bool> qjsDropRuntime(String runtimeName) async {
    final _payload = ByteWriter();
    _payload.str(runtimeName);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(qjsDropRuntimeId, _payloadBytes);
    return ByteReader(_bytes).u8() != 0;
  }

  int add(int a, int b) {
    final _payload = ByteWriter();
    _payload.i32(a);
    _payload.i32(b);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(addId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<Uint8List> qjsTaskCall(String runtimeName, String taskGroupKey, bool isOnce, String? bundleJs, String fnPath, String argsJson) async {
    final _payload = ByteWriter();
    _payload.str(runtimeName);
    _payload.str(taskGroupKey);
    _payload.u8(isOnce ? 1 : 0);
    if (bundleJs == null) { _payload.u8(0); } else { _payload.u8(1);
      _payload.str(bundleJs);
    }
    _payload.str(fnPath);
    _payload.str(argsJson);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(qjsTaskCallId, _payloadBytes);
    return (() { final _r = ByteReader(_bytes); return _r.u8vec(); })();
  }

  Future<String> fetchGreeting(String name) async {
    final _payload = ByteWriter();
    _payload.str(name);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(fetchGreetingId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  void qjsSetTlsVerifyEnabled(bool enabled) {
    final _payload = ByteWriter();
    _payload.u8(enabled ? 1 : 0);
    final _payloadBytes = _payload.takeBytes();
    bridge.invokeSyncMethod(qjsSetTlsVerifyEnabledId, _payloadBytes);
  }

  Future<void> qjsReplaceBundle(String runtimeName, String bundleName, String bundleJs) async {
    final _payload = ByteWriter();
    _payload.str(runtimeName);
    _payload.str(bundleName);
    _payload.str(bundleJs);
    final _payloadBytes = _payload.takeBytes();
    await bridge.invokeAsyncMethod(qjsReplaceBundleId, _payloadBytes);
  }

  Future<String> qjsCurrentBundle(String runtimeName) async {
    final _payload = ByteWriter();
    _payload.str(runtimeName);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(qjsCurrentBundleId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  WindHttpClient windHttpClientNewWithDefaultHeaders(Map<String, String> defaultHeaders, int timeoutMs, bool followRedirects, String proxy, bool tlsVerify, String userAgent) {
    final _payload = ByteWriter();
    _payload.u32(defaultHeaders.length);
    defaultHeaders.forEach((final _k, final _v) {
      _payload.str(_k);
      _payload.str(_v);
    });
    _payload.i64(timeoutMs);
    _payload.u8(followRedirects ? 1 : 0);
    _payload.str(proxy);
    _payload.u8(tlsVerify ? 1 : 0);
    _payload.str(userAgent);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(windHttpClientNewWithDefaultHeadersId, _payloadBytes);
    return WindHttpClient.fromHandle(bridge: bridge, handle: ByteReader(_bytes).u64());
  }

  Future<WindFetchResponse> windHttpClientFetch(WindHttpClient self, String url, WindFetchInit init) async {
    self.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(self.handle);
    _payload.str(url);
    _writeDataClass_WindFetchInit(_payload, init);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(windHttpClientFetchId, _payloadBytes);
    return _readDataClass_WindFetchResponse(ByteReader(_bytes));
  }

  Future<void> windHttpClientDownload(WindHttpClient self, String url, String savePath, WindFetchInit init, StreamController<WindDownloadProgress>? progress) async {
    self.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(self.handle);
    _payload.str(url);
    _payload.str(savePath);
    _writeDataClass_WindFetchInit(_payload, init);
    await bridge.invokeAsyncMethodWithStream<WindDownloadProgress>(windHttpClientDownloadId, _payload, progress, (final _r) => _readDataClass_WindDownloadProgress(_r));
  }

  int windHttpClientAliveCount() {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(windHttpClientAliveCountId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }
}
