// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bika.dart';
import 'api/memory.dart';
import 'api/simple.dart';
import 'api/system.dart';
import 'api/user_utils.dart';
import 'compressed/compressed.dart';
import 'dart:async';
import 'dart:convert';
import 'decode/decode.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -749789986;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'windcore',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleAntiObfuscationPicture({
    required ImageInfo imageInfo,
  });

  Future<String> crateApiBikaBikaFavouriteComic({required String comicId});

  Future<String> crateApiBikaBikaGetCategories();

  Future<String> crateApiBikaBikaGetComicInfo({
    required String comicId,
    String? authorization,
    String? imageQuality,
  });

  Future<String> crateApiBikaBikaGetComments({
    required String comicId,
    required int pageCount,
  });

  Future<String> crateApiBikaBikaGetCommentsChildren({
    required String commentId,
    required int pageCount,
  });

  Future<String> crateApiBikaBikaGetEps({
    required String comicId,
    required int pageCount,
    String? authorization,
    String? imageQuality,
  });

  Future<String> crateApiBikaBikaGetFavorites({required int pageCount});

  Future<String> crateApiBikaBikaGetPages({
    required String comicId,
    required int epId,
    required int pageCount,
    String? authorization,
    String? imageQuality,
  });

  Future<String> crateApiBikaBikaGetRankingList({
    required String days,
    required String kind,
  });

  Future<String> crateApiBikaBikaGetRecommend({required String comicId});

  Future<String> crateApiBikaBikaGetSearchKeywords();

  Future<String> crateApiBikaBikaGetUserComments({required int pageCount});

  Future<String> crateApiBikaBikaGetUserProfile();

  Future<String> crateApiBikaBikaLikeComic({required String comicId});

  Future<String> crateApiBikaBikaLikeComment({required String commentId});

  Future<String> crateApiBikaBikaLogin({
    required String username,
    required String password,
  });

  Future<String> crateApiBikaBikaRegister({
    required String birthday,
    required String email,
    required String gender,
    required String name,
    required String password,
  });

  Future<String> crateApiBikaBikaReportComments({required String commentId});

  Future<String> crateApiBikaBikaRequestRaw({
    required String url,
    required String method,
    String? bodyJson,
    String? imageQuality,
    String? authorization,
  });

  Future<String> crateApiBikaBikaSearch({
    required String url,
    required String keyword,
    required String sort,
    required List<String> categories,
    required int pageCount,
  });

  Future<String> crateApiBikaBikaSignIn();

  Future<String> crateApiBikaBikaUpdateAvatar({
    required String avatarBase64String,
  });

  Future<String> crateApiBikaBikaUpdatePassword({
    required String newPassword,
    required String oldPassword,
  });

  Future<String> crateApiBikaBikaUpdateProfile({required String profile});

  Future<String> crateApiBikaBikaWriteComment({
    required String comicId,
    required String content,
  });

  Future<String> crateApiBikaBikaWriteCommentChildren({
    required String commentId,
    required String content,
  });

  Future<String> crateApiSimpleCompressImage({required List<int> imageBytes});

  Future<RustMemoryInfo> crateApiMemoryGetRustMemoryInfo();

  Future<String> crateApiMemoryGetRustMemorySummary();

  Future<String> crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiSimplePackFolder({
    required String destPath,
    required PackInfo packInfo,
  });

  Future<void> crateApiSimplePackFolderZip({
    required String destPath,
    required PackInfo packInfo,
  });

  Future<void> crateApiMemoryResetRustMemoryStats();

  Future<void> crateApiUserUtilsSetupDefaultUserUtils();

  Future<String> crateApiSimpleSleepTest();

  Stream<bool> crateApiSystemStartShutdownListener();

  Stream<String> crateApiSimpleStreamTest();

  String crateApiSimpleTraditionalToSimplified({required String text});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleAntiObfuscationPicture({
    required ImageInfo imageInfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_image_info(imageInfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAntiObfuscationPictureConstMeta,
        argValues: [imageInfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAntiObfuscationPictureConstMeta =>
      const TaskConstMeta(
        debugName: "anti_obfuscation_picture",
        argNames: ["imageInfo"],
      );

  @override
  Future<String> crateApiBikaBikaFavouriteComic({required String comicId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaFavouriteComicConstMeta,
        argValues: [comicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaFavouriteComicConstMeta =>
      const TaskConstMeta(
        debugName: "bika_favourite_comic",
        argNames: ["comicId"],
      );

  @override
  Future<String> crateApiBikaBikaGetCategories() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaGetCategoriesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaGetCategoriesConstMeta =>
      const TaskConstMeta(debugName: "bika_get_categories", argNames: []);

  @override
  Future<String> crateApiBikaBikaGetComicInfo({
    required String comicId,
    String? authorization,
    String? imageQuality,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          sse_encode_opt_String(authorization, serializer);
          sse_encode_opt_String(imageQuality, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaGetComicInfoConstMeta,
        argValues: [comicId, authorization, imageQuality],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaGetComicInfoConstMeta =>
      const TaskConstMeta(
        debugName: "bika_get_comic_info",
        argNames: ["comicId", "authorization", "imageQuality"],
      );

  @override
  Future<String> crateApiBikaBikaGetComments({
    required String comicId,
    required int pageCount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          sse_encode_i_32(pageCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaGetCommentsConstMeta,
        argValues: [comicId, pageCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaGetCommentsConstMeta =>
      const TaskConstMeta(
        debugName: "bika_get_comments",
        argNames: ["comicId", "pageCount"],
      );

  @override
  Future<String> crateApiBikaBikaGetCommentsChildren({
    required String commentId,
    required int pageCount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(commentId, serializer);
          sse_encode_i_32(pageCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaGetCommentsChildrenConstMeta,
        argValues: [commentId, pageCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaGetCommentsChildrenConstMeta =>
      const TaskConstMeta(
        debugName: "bika_get_comments_children",
        argNames: ["commentId", "pageCount"],
      );

  @override
  Future<String> crateApiBikaBikaGetEps({
    required String comicId,
    required int pageCount,
    String? authorization,
    String? imageQuality,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          sse_encode_i_32(pageCount, serializer);
          sse_encode_opt_String(authorization, serializer);
          sse_encode_opt_String(imageQuality, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaGetEpsConstMeta,
        argValues: [comicId, pageCount, authorization, imageQuality],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaGetEpsConstMeta => const TaskConstMeta(
    debugName: "bika_get_eps",
    argNames: ["comicId", "pageCount", "authorization", "imageQuality"],
  );

  @override
  Future<String> crateApiBikaBikaGetFavorites({required int pageCount}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(pageCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaGetFavoritesConstMeta,
        argValues: [pageCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaGetFavoritesConstMeta =>
      const TaskConstMeta(
        debugName: "bika_get_favorites",
        argNames: ["pageCount"],
      );

  @override
  Future<String> crateApiBikaBikaGetPages({
    required String comicId,
    required int epId,
    required int pageCount,
    String? authorization,
    String? imageQuality,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          sse_encode_i_32(epId, serializer);
          sse_encode_i_32(pageCount, serializer);
          sse_encode_opt_String(authorization, serializer);
          sse_encode_opt_String(imageQuality, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaGetPagesConstMeta,
        argValues: [comicId, epId, pageCount, authorization, imageQuality],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaGetPagesConstMeta => const TaskConstMeta(
    debugName: "bika_get_pages",
    argNames: ["comicId", "epId", "pageCount", "authorization", "imageQuality"],
  );

  @override
  Future<String> crateApiBikaBikaGetRankingList({
    required String days,
    required String kind,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(days, serializer);
          sse_encode_String(kind, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaGetRankingListConstMeta,
        argValues: [days, kind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaGetRankingListConstMeta =>
      const TaskConstMeta(
        debugName: "bika_get_ranking_list",
        argNames: ["days", "kind"],
      );

  @override
  Future<String> crateApiBikaBikaGetRecommend({required String comicId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaGetRecommendConstMeta,
        argValues: [comicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaGetRecommendConstMeta =>
      const TaskConstMeta(
        debugName: "bika_get_recommend",
        argNames: ["comicId"],
      );

  @override
  Future<String> crateApiBikaBikaGetSearchKeywords() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaGetSearchKeywordsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaGetSearchKeywordsConstMeta =>
      const TaskConstMeta(debugName: "bika_get_search_keywords", argNames: []);

  @override
  Future<String> crateApiBikaBikaGetUserComments({required int pageCount}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(pageCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaGetUserCommentsConstMeta,
        argValues: [pageCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaGetUserCommentsConstMeta =>
      const TaskConstMeta(
        debugName: "bika_get_user_comments",
        argNames: ["pageCount"],
      );

  @override
  Future<String> crateApiBikaBikaGetUserProfile() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaGetUserProfileConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaGetUserProfileConstMeta =>
      const TaskConstMeta(debugName: "bika_get_user_profile", argNames: []);

  @override
  Future<String> crateApiBikaBikaLikeComic({required String comicId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaLikeComicConstMeta,
        argValues: [comicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaLikeComicConstMeta =>
      const TaskConstMeta(debugName: "bika_like_comic", argNames: ["comicId"]);

  @override
  Future<String> crateApiBikaBikaLikeComment({required String commentId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(commentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaLikeCommentConstMeta,
        argValues: [commentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaLikeCommentConstMeta =>
      const TaskConstMeta(
        debugName: "bika_like_comment",
        argNames: ["commentId"],
      );

  @override
  Future<String> crateApiBikaBikaLogin({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaLoginConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaLoginConstMeta => const TaskConstMeta(
    debugName: "bika_login",
    argNames: ["username", "password"],
  );

  @override
  Future<String> crateApiBikaBikaRegister({
    required String birthday,
    required String email,
    required String gender,
    required String name,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(birthday, serializer);
          sse_encode_String(email, serializer);
          sse_encode_String(gender, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaRegisterConstMeta,
        argValues: [birthday, email, gender, name, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaRegisterConstMeta => const TaskConstMeta(
    debugName: "bika_register",
    argNames: ["birthday", "email", "gender", "name", "password"],
  );

  @override
  Future<String> crateApiBikaBikaReportComments({required String commentId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(commentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaReportCommentsConstMeta,
        argValues: [commentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaReportCommentsConstMeta =>
      const TaskConstMeta(
        debugName: "bika_report_comments",
        argNames: ["commentId"],
      );

  @override
  Future<String> crateApiBikaBikaRequestRaw({
    required String url,
    required String method,
    String? bodyJson,
    String? imageQuality,
    String? authorization,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(method, serializer);
          sse_encode_opt_String(bodyJson, serializer);
          sse_encode_opt_String(imageQuality, serializer);
          sse_encode_opt_String(authorization, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaRequestRawConstMeta,
        argValues: [url, method, bodyJson, imageQuality, authorization],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaRequestRawConstMeta => const TaskConstMeta(
    debugName: "bika_request_raw",
    argNames: ["url", "method", "bodyJson", "imageQuality", "authorization"],
  );

  @override
  Future<String> crateApiBikaBikaSearch({
    required String url,
    required String keyword,
    required String sort,
    required List<String> categories,
    required int pageCount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(keyword, serializer);
          sse_encode_String(sort, serializer);
          sse_encode_list_String(categories, serializer);
          sse_encode_i_32(pageCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaSearchConstMeta,
        argValues: [url, keyword, sort, categories, pageCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaSearchConstMeta => const TaskConstMeta(
    debugName: "bika_search",
    argNames: ["url", "keyword", "sort", "categories", "pageCount"],
  );

  @override
  Future<String> crateApiBikaBikaSignIn() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaSignInConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaSignInConstMeta =>
      const TaskConstMeta(debugName: "bika_sign_in", argNames: []);

  @override
  Future<String> crateApiBikaBikaUpdateAvatar({
    required String avatarBase64String,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(avatarBase64String, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaUpdateAvatarConstMeta,
        argValues: [avatarBase64String],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaUpdateAvatarConstMeta =>
      const TaskConstMeta(
        debugName: "bika_update_avatar",
        argNames: ["avatarBase64String"],
      );

  @override
  Future<String> crateApiBikaBikaUpdatePassword({
    required String newPassword,
    required String oldPassword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(newPassword, serializer);
          sse_encode_String(oldPassword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaUpdatePasswordConstMeta,
        argValues: [newPassword, oldPassword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaUpdatePasswordConstMeta =>
      const TaskConstMeta(
        debugName: "bika_update_password",
        argNames: ["newPassword", "oldPassword"],
      );

  @override
  Future<String> crateApiBikaBikaUpdateProfile({required String profile}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaUpdateProfileConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaUpdateProfileConstMeta =>
      const TaskConstMeta(
        debugName: "bika_update_profile",
        argNames: ["profile"],
      );

  @override
  Future<String> crateApiBikaBikaWriteComment({
    required String comicId,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaWriteCommentConstMeta,
        argValues: [comicId, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaWriteCommentConstMeta =>
      const TaskConstMeta(
        debugName: "bika_write_comment",
        argNames: ["comicId", "content"],
      );

  @override
  Future<String> crateApiBikaBikaWriteCommentChildren({
    required String commentId,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(commentId, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBikaBikaWriteCommentChildrenConstMeta,
        argValues: [commentId, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBikaBikaWriteCommentChildrenConstMeta =>
      const TaskConstMeta(
        debugName: "bika_write_comment_children",
        argNames: ["commentId", "content"],
      );

  @override
  Future<String> crateApiSimpleCompressImage({required List<int> imageBytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleCompressImageConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCompressImageConstMeta =>
      const TaskConstMeta(
        debugName: "compress_image",
        argNames: ["imageBytes"],
      );

  @override
  Future<RustMemoryInfo> crateApiMemoryGetRustMemoryInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_memory_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMemoryGetRustMemoryInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryGetRustMemoryInfoConstMeta =>
      const TaskConstMeta(debugName: "get_rust_memory_info", argNames: []);

  @override
  Future<String> crateApiMemoryGetRustMemorySummary() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMemoryGetRustMemorySummaryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryGetRustMemorySummaryConstMeta =>
      const TaskConstMeta(debugName: "get_rust_memory_summary", argNames: []);

  @override
  Future<String> crateApiSimpleGreet({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiSimplePackFolder({
    required String destPath,
    required PackInfo packInfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(destPath, serializer);
          sse_encode_box_autoadd_pack_info(packInfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimplePackFolderConstMeta,
        argValues: [destPath, packInfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePackFolderConstMeta => const TaskConstMeta(
    debugName: "pack_folder",
    argNames: ["destPath", "packInfo"],
  );

  @override
  Future<void> crateApiSimplePackFolderZip({
    required String destPath,
    required PackInfo packInfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(destPath, serializer);
          sse_encode_box_autoadd_pack_info(packInfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimplePackFolderZipConstMeta,
        argValues: [destPath, packInfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePackFolderZipConstMeta =>
      const TaskConstMeta(
        debugName: "pack_folder_zip",
        argNames: ["destPath", "packInfo"],
      );

  @override
  Future<void> crateApiMemoryResetRustMemoryStats() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMemoryResetRustMemoryStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryResetRustMemoryStatsConstMeta =>
      const TaskConstMeta(debugName: "reset_rust_memory_stats", argNames: []);

  @override
  Future<void> crateApiUserUtilsSetupDefaultUserUtils() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUserUtilsSetupDefaultUserUtilsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserUtilsSetupDefaultUserUtilsConstMeta =>
      const TaskConstMeta(debugName: "setup_default_user_utils", argNames: []);

  @override
  Future<String> crateApiSimpleSleepTest() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleSleepTestConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSleepTestConstMeta =>
      const TaskConstMeta(debugName: "sleep_test", argNames: []);

  @override
  Stream<bool> crateApiSystemStartShutdownListener() {
    final sink = RustStreamSink<bool>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_bool_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 38,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSystemStartShutdownListenerConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSystemStartShutdownListenerConstMeta =>
      const TaskConstMeta(
        debugName: "start_shutdown_listener",
        argNames: ["sink"],
      );

  @override
  Stream<String> crateApiSimpleStreamTest() {
    final stream = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(stream, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 39,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSimpleStreamTestConstMeta,
          argValues: [stream],
          apiImpl: this,
        ),
      ),
    );
    return stream.stream;
  }

  TaskConstMeta get kCrateApiSimpleStreamTestConstMeta =>
      const TaskConstMeta(debugName: "stream_test", argNames: ["stream"]);

  @override
  String crateApiSimpleTraditionalToSimplified({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTraditionalToSimplifiedConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTraditionalToSimplifiedConstMeta =>
      const TaskConstMeta(
        debugName: "traditional_to_simplified",
        argNames: ["text"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<bool> dco_decode_StreamSink_bool_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ImageInfo dco_decode_box_autoadd_image_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_image_info(raw);
  }

  @protected
  PackInfo dco_decode_box_autoadd_pack_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pack_info(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ImageInfo dco_decode_image_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ImageInfo(
      imgData: dco_decode_list_prim_u_8_strict(arr[0]),
      chapterId: dco_decode_i_32(arr[1]),
      url: dco_decode_String(arr[2]),
      scrambleId: dco_decode_i_32(arr[3]),
      fileName: dco_decode_String(arr[4]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TaggedAllocation> dco_decode_list_tagged_allocation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tagged_allocation).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PackInfo dco_decode_pack_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PackInfo(
      comicInfoString: dco_decode_String(arr[0]),
      processedComicInfoString: dco_decode_String(arr[1]),
      originalImagePaths: dco_decode_list_String(arr[2]),
      packImagePaths: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  RustMemoryInfo dco_decode_rust_memory_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RustMemoryInfo(
      totalAllocated: dco_decode_u_64(arr[0]),
      peakAllocated: dco_decode_u_64(arr[1]),
      allocationCount: dco_decode_u_64(arr[2]),
      deallocationCount: dco_decode_u_64(arr[3]),
      taggedAllocations: dco_decode_list_tagged_allocation(arr[4]),
    );
  }

  @protected
  TaggedAllocation dco_decode_tagged_allocation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TaggedAllocation(
      tag: dco_decode_String(arr[0]),
      size: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<bool> sse_decode_StreamSink_bool_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ImageInfo sse_decode_box_autoadd_image_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_image_info(deserializer));
  }

  @protected
  PackInfo sse_decode_box_autoadd_pack_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pack_info(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ImageInfo sse_decode_image_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_imgData = sse_decode_list_prim_u_8_strict(deserializer);
    var var_chapterId = sse_decode_i_32(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_scrambleId = sse_decode_i_32(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    return ImageInfo(
      imgData: var_imgData,
      chapterId: var_chapterId,
      url: var_url,
      scrambleId: var_scrambleId,
      fileName: var_fileName,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TaggedAllocation> sse_decode_list_tagged_allocation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TaggedAllocation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tagged_allocation(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PackInfo sse_decode_pack_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_comicInfoString = sse_decode_String(deserializer);
    var var_processedComicInfoString = sse_decode_String(deserializer);
    var var_originalImagePaths = sse_decode_list_String(deserializer);
    var var_packImagePaths = sse_decode_list_String(deserializer);
    return PackInfo(
      comicInfoString: var_comicInfoString,
      processedComicInfoString: var_processedComicInfoString,
      originalImagePaths: var_originalImagePaths,
      packImagePaths: var_packImagePaths,
    );
  }

  @protected
  RustMemoryInfo sse_decode_rust_memory_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalAllocated = sse_decode_u_64(deserializer);
    var var_peakAllocated = sse_decode_u_64(deserializer);
    var var_allocationCount = sse_decode_u_64(deserializer);
    var var_deallocationCount = sse_decode_u_64(deserializer);
    var var_taggedAllocations = sse_decode_list_tagged_allocation(deserializer);
    return RustMemoryInfo(
      totalAllocated: var_totalAllocated,
      peakAllocated: var_peakAllocated,
      allocationCount: var_allocationCount,
      deallocationCount: var_deallocationCount,
      taggedAllocations: var_taggedAllocations,
    );
  }

  @protected
  TaggedAllocation sse_decode_tagged_allocation(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tag = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    return TaggedAllocation(tag: var_tag, size: var_size);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_bool_Sse(
    RustStreamSink<bool> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_image_info(
    ImageInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pack_info(
    PackInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pack_info(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_image_info(ImageInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.imgData, serializer);
    sse_encode_i_32(self.chapterId, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_i_32(self.scrambleId, serializer);
    sse_encode_String(self.fileName, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_tagged_allocation(
    List<TaggedAllocation> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tagged_allocation(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_pack_info(PackInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.comicInfoString, serializer);
    sse_encode_String(self.processedComicInfoString, serializer);
    sse_encode_list_String(self.originalImagePaths, serializer);
    sse_encode_list_String(self.packImagePaths, serializer);
  }

  @protected
  void sse_encode_rust_memory_info(
    RustMemoryInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.totalAllocated, serializer);
    sse_encode_u_64(self.peakAllocated, serializer);
    sse_encode_u_64(self.allocationCount, serializer);
    sse_encode_u_64(self.deallocationCount, serializer);
    sse_encode_list_tagged_allocation(self.taggedAllocations, serializer);
  }

  @protected
  void sse_encode_tagged_allocation(
    TaggedAllocation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tag, serializer);
    sse_encode_u_64(self.size, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
