// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class QjsCancelTaskResult {
  final String status;

  const QjsCancelTaskResult({required this.status});

  @override
  int get hashCode => status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QjsCancelTaskResult &&
          runtimeType == other.runtimeType &&
          status == other.status;
}

class QjsCancelTasksByGroupResult {
  final int cancelled;
  final int notFound;
  final List<String> failedRuntimeGroups;

  const QjsCancelTasksByGroupResult({
    required this.cancelled,
    required this.notFound,
    required this.failedRuntimeGroups,
  });

  @override
  int get hashCode =>
      cancelled.hashCode ^ notFound.hashCode ^ failedRuntimeGroups.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QjsCancelTasksByGroupResult &&
          runtimeType == other.runtimeType &&
          cancelled == other.cancelled &&
          notFound == other.notFound &&
          failedRuntimeGroups == other.failedRuntimeGroups;
}

class QjsRuntimeBuildRequest {
  final String runtimeName;
  final bool injectFilesystem;
  final bool enableWasi;
  final QjsRuntimeBundleBuild? bundle;

  const QjsRuntimeBuildRequest({
    required this.runtimeName,
    required this.injectFilesystem,
    required this.enableWasi,
    this.bundle,
  });

  @override
  int get hashCode =>
      runtimeName.hashCode ^
      injectFilesystem.hashCode ^
      enableWasi.hashCode ^
      bundle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QjsRuntimeBuildRequest &&
          runtimeType == other.runtimeType &&
          runtimeName == other.runtimeName &&
          injectFilesystem == other.injectFilesystem &&
          enableWasi == other.enableWasi &&
          bundle == other.bundle;
}

class QjsRuntimeBundleBuild {
  final String bundleName;
  final String bundleJs;

  const QjsRuntimeBundleBuild({
    required this.bundleName,
    required this.bundleJs,
  });

  @override
  int get hashCode => bundleName.hashCode ^ bundleJs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QjsRuntimeBundleBuild &&
          runtimeType == other.runtimeType &&
          bundleName == other.bundleName &&
          bundleJs == other.bundleJs;
}
