// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return windows;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return windows;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_ANDROID', fallback: ''),
    appId: dotenv.get('FIREBASE_APP_ID_ANDROID', fallback: ''),
    messagingSenderId: dotenv.get(
      'FIREBASE_MESSAGING_SENDER_ID_ANDROID',
      fallback: '',
    ),
    projectId: dotenv.get('FIREBASE_PROJECT_ID_ANDROID', fallback: ''),
    storageBucket: dotenv.get('FIREBASE_STORAGE_BUCKET_ANDROID', fallback: ''),
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_WINDOWS', fallback: ''),
    authDomain: dotenv.get('FIREBASE_AUTH_DOMAIN_WINDOWS', fallback: ''),
    projectId: dotenv.get('FIREBASE_PROJECT_ID_WINDOWS', fallback: ''),
    storageBucket: dotenv.get('FIREBASE_STORAGE_BUCKET_WINDOWS', fallback: ''),
    messagingSenderId: dotenv.get(
      'FIREBASE_MESSAGING_SENDER_ID_WINDOWS',
      fallback: '',
    ),
    appId: dotenv.get('FIREBASE_APP_ID_WINDOWS', fallback: ''),
    measurementId: dotenv.get('FIREBASE_MEASUREMENT_ID_WINDOWS', fallback: ''),
  );
}
