// GENERATED by dart_cpp_bridge codegen — do not edit.
// Source: bridge_api.h

import 'package:zephyr/src/native_gen/dcb_generated.dart';

// ═════════════════════════════════════════════
// Functions
// ═════════════════════════════════════════════

Future<String> heavyCompute({required int input}) =>
    BridgeApiImpl.instance.heavyCompute(input);

int add({required int a, required int b}) => BridgeApiImpl.instance.add(a, b);

Future<String> fetchGreeting({required String name}) =>
    BridgeApiImpl.instance.fetchGreeting(name);
