// GENERATED by dart_cpp_bridge codegen — do not edit.

import 'package:dart_cpp_bridge/dart_cpp_bridge.dart';

import '../dcb_bindings.dart';
import '../dcb_generated.dart';

/// dart_cpp_bridge management class.
///
/// Usage:
/// ```dart
/// await DcbLib.init();
/// final v = bridgeVersion();
/// DcbLib.shutdown(); // only on process exit
/// ```
final class DcbLib {
  DcbLib._();

  static DartCppBridge? _bridge;

  /// Whether the bridge has been initialized.
  static bool get isInitialized => _bridge != null;

  /// Underlying bridge instance (available after init).
  static DartCppBridge get bridge {
    final b = _bridge;
    if (b == null) throw StateError('DcbLib.init() must be called first');
    return b;
  }

  /// Initialize (call once per Isolate).
  ///
  /// [threadPoolSize] sets the native thread pool concurrency (default 4).
  /// [verboseErrors] controls whether C++ errors include function names (default true).
  static Future<void> init({int threadPoolSize = 4, bool verboseErrors = true}) async {
    if (_bridge != null) return;
    final b = await DartCppBridge.init(bindings: createDcbBindings(), poolThreads: threadPoolSize);
    b.setVerboseErrors(verboseErrors);
    _bridge = b;
    BridgeApiImpl.initSingleton(b);
  }

  /// Close this Isolate's session (optional; Finalizer also closes).
  static void dispose() {
    _bridge?.dispose();
    _bridge = null;
    BridgeApiImpl.disposeSingleton();
  }

  /// Process-wide shutdown (main Isolate / app exit only).
  static void shutdown() {
    _bridge?.shutdown();
    _bridge = null;
    BridgeApiImpl.disposeSingleton();
  }

  /// Enable or disable verbose error messages (default: enabled).
  ///
  /// When enabled, C++ error messages are prefixed with `[function_name] `.
  static void setVerboseErrors(bool enabled) {
    bridge.setVerboseErrors(enabled);
  }
}
