# --- Find dart_cpp_bridge (reads .dart_tool/package_config.json) ---
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/../.dart_tool/package_config.json" _j)
string(JSON _c LENGTH "${_j}" "packages")
math(EXPR _e "${_c} - 1")
foreach(_i RANGE ${_e})
  string(JSON _n GET "${_j}" "packages" ${_i} "name")
  if(_n STREQUAL "dart_cpp_bridge")
    string(JSON _u GET "${_j}" "packages" ${_i} "rootUri")
    break()
  endif()
endforeach()
if(NOT DEFINED _u)
  message(FATAL_ERROR "dart_cpp_bridge not in package_config.json")
endif()
if(_u MATCHES "^file://")
  if(WIN32)
    # file:///C:/... -> C:/... (drive letter keeps the path absolute)
    string(REGEX REPLACE "^file:///" "" DCB_PKG_PATH "${_u}")
  else()
    # file:///home/... -> /home/... (keep the leading root slash)
    string(REGEX REPLACE "^file://" "" DCB_PKG_PATH "${_u}")
  endif()
else()
  get_filename_component(DCB_PKG_PATH
    "${CMAKE_CURRENT_SOURCE_DIR}/../.dart_tool/${_u}" ABSOLUTE)
endif()
include("${DCB_PKG_PATH}/native/cmake/dcb_find_package.cmake")
add_subdirectory(${DCB_ROOT} ${CMAKE_CURRENT_BINARY_DIR}/dcb_runtime)

# --- Generated wire check ---
set(GEN_WIRE "${CMAKE_CURRENT_SOURCE_DIR}/generated/wire_dispatch.cpp")
if(NOT EXISTS "${GEN_WIRE}")
  message(FATAL_ERROR
    "Missing generated wire. Run: dcb_gen_tool generate dart_cpp_bridge.yaml")
endif()
