// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `auth_cache_path`, `auth_cache`, `bika_request`, `build_url`, `default_app_channel`, `default_image_quality`, `extract_auth_token`, `get_cached_authorization`, `persist_auth_to_disk`, `read_auth_from_disk`, `resolve_authorization`, `run_qjs_dispatch`, `set_cached_authorization`

Future<String> bikaLogin({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiBikaBikaLogin(
  username: username,
  password: password,
);

Future<String> bikaRegister({
  required String birthday,
  required String email,
  required String gender,
  required String name,
  required String password,
}) => RustLib.instance.api.crateApiBikaBikaRegister(
  birthday: birthday,
  email: email,
  gender: gender,
  name: name,
  password: password,
);

Future<String> bikaGetCategories() =>
    RustLib.instance.api.crateApiBikaBikaGetCategories();

Future<String> bikaGetRankingList({
  required String days,
  required String kind,
}) =>
    RustLib.instance.api.crateApiBikaBikaGetRankingList(days: days, kind: kind);

Future<String> bikaSearch({
  required String url,
  required String keyword,
  required String sort,
  required List<String> categories,
  required int pageCount,
}) => RustLib.instance.api.crateApiBikaBikaSearch(
  url: url,
  keyword: keyword,
  sort: sort,
  categories: categories,
  pageCount: pageCount,
);

Future<String> bikaGetSearchKeywords() =>
    RustLib.instance.api.crateApiBikaBikaGetSearchKeywords();

Future<String> bikaGetComicInfo({
  required String comicId,
  String? authorization,
  String? imageQuality,
}) => RustLib.instance.api.crateApiBikaBikaGetComicInfo(
  comicId: comicId,
  authorization: authorization,
  imageQuality: imageQuality,
);

Future<String> bikaFavouriteComic({required String comicId}) =>
    RustLib.instance.api.crateApiBikaBikaFavouriteComic(comicId: comicId);

Future<String> bikaLikeComic({required String comicId}) =>
    RustLib.instance.api.crateApiBikaBikaLikeComic(comicId: comicId);

Future<String> bikaGetComments({
  required String comicId,
  required int pageCount,
}) => RustLib.instance.api.crateApiBikaBikaGetComments(
  comicId: comicId,
  pageCount: pageCount,
);

Future<String> bikaGetCommentsChildren({
  required String commentId,
  required int pageCount,
}) => RustLib.instance.api.crateApiBikaBikaGetCommentsChildren(
  commentId: commentId,
  pageCount: pageCount,
);

Future<String> bikaLikeComment({required String commentId}) =>
    RustLib.instance.api.crateApiBikaBikaLikeComment(commentId: commentId);

Future<String> bikaWriteComment({
  required String comicId,
  required String content,
}) => RustLib.instance.api.crateApiBikaBikaWriteComment(
  comicId: comicId,
  content: content,
);

Future<String> bikaWriteCommentChildren({
  required String commentId,
  required String content,
}) => RustLib.instance.api.crateApiBikaBikaWriteCommentChildren(
  commentId: commentId,
  content: content,
);

Future<String> bikaReportComments({required String commentId}) =>
    RustLib.instance.api.crateApiBikaBikaReportComments(commentId: commentId);

Future<String> bikaGetEps({
  required String comicId,
  required int pageCount,
  String? authorization,
  String? imageQuality,
}) => RustLib.instance.api.crateApiBikaBikaGetEps(
  comicId: comicId,
  pageCount: pageCount,
  authorization: authorization,
  imageQuality: imageQuality,
);

Future<String> bikaGetRecommend({required String comicId}) =>
    RustLib.instance.api.crateApiBikaBikaGetRecommend(comicId: comicId);

Future<String> bikaGetPages({
  required String comicId,
  required int epId,
  required int pageCount,
  String? authorization,
  String? imageQuality,
}) => RustLib.instance.api.crateApiBikaBikaGetPages(
  comicId: comicId,
  epId: epId,
  pageCount: pageCount,
  authorization: authorization,
  imageQuality: imageQuality,
);

Future<String> bikaGetUserProfile() =>
    RustLib.instance.api.crateApiBikaBikaGetUserProfile();

Future<String> bikaUpdateAvatar({required String avatarBase64String}) => RustLib
    .instance
    .api
    .crateApiBikaBikaUpdateAvatar(avatarBase64String: avatarBase64String);

Future<String> bikaUpdateProfile({required String profile}) =>
    RustLib.instance.api.crateApiBikaBikaUpdateProfile(profile: profile);

Future<String> bikaUpdatePassword({
  required String newPassword,
  required String oldPassword,
}) => RustLib.instance.api.crateApiBikaBikaUpdatePassword(
  newPassword: newPassword,
  oldPassword: oldPassword,
);

Future<String> bikaGetFavorites({required int pageCount}) =>
    RustLib.instance.api.crateApiBikaBikaGetFavorites(pageCount: pageCount);

Future<String> bikaGetUserComments({required int pageCount}) =>
    RustLib.instance.api.crateApiBikaBikaGetUserComments(pageCount: pageCount);

Future<String> bikaSignIn() => RustLib.instance.api.crateApiBikaBikaSignIn();

Future<String> bikaRequestRaw({
  required String url,
  required String method,
  String? bodyJson,
  String? imageQuality,
  String? authorization,
}) => RustLib.instance.api.crateApiBikaBikaRequestRaw(
  url: url,
  method: method,
  bodyJson: bodyJson,
  imageQuality: imageQuality,
  authorization: authorization,
);
