// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_directory_to_zip`, `add_file_to_zip`

/// 流式创建应用数据备份 zip。
///
/// - `data_dir` 下的所有文件/目录会放到 zip 根目录；Dart 侧应在这里准备好
///   `config.json` 与 `objectbox.json`。
/// - 若 `download_dir` 不为空，则其下所有内容会以 `downloads/` 为前缀打包。
/// - 全部使用 Stored（不压缩）方式写入，避免对图片等已压缩数据做无效压缩。
Future<void> createDataBackupZip({
  required String zipPath,
  required String dataDir,
  String? downloadDir,
}) => RustLib.instance.api.crateApiDataBackupCreateDataBackupZip(
  zipPath: zipPath,
  dataDir: dataDir,
  downloadDir: downloadDir,
);

/// 将数据备份 zip 解压到目标目录。
Future<void> extractDataBackupZip({
  required String zipPath,
  required String extractDir,
}) => RustLib.instance.api.crateApiDataBackupExtractDataBackupZip(
  zipPath: zipPath,
  extractDir: extractDir,
);
