// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`, `from`, `from`, `from`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `new`

class FrbError implements FrbException {
  final String message;

  const FrbError({required this.message});

  @override
  String toString() =>
      RustLib.instance.api.crateApiErrorFrbErrorToStringMethod(that: this);

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}
