// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_default_headers`, `apply_headers`, `create_reqwest_client`, `flatten_headers`, `resolve_url`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// 快捷入口：每次新建客户端后 `fetch`。
Future<FetchResponse> fetch({required String url, FetchInit? init}) =>
    RustLib.instance.api.crateApiHttpFetch(url: url, init: init);

/// 快捷入口：每次新建直连客户端后 `fetch`。
Future<FetchResponse> fetchDirect({required String url, FetchInit? init}) =>
    RustLib.instance.api.crateApiHttpFetchDirect(url: url, init: init);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HttpClient>>
abstract class HttpClient implements RustOpaqueInterface {
  String baseUrl();

  static HttpClient create({HttpClientOptions? options}) =>
      RustLib.instance.api.crateApiHttpHttpClientCreate(options: options);

  Map<String, String> defaultHeaders();

  static HttpClient direct() =>
      RustLib.instance.api.crateApiHttpHttpClientDirect();

  /// 下载到本地文件（流式写盘）。
  Future<void> download({
    required String url,
    required String savePath,
    FetchInit? init,
    RustStreamSink<HttpProgress>? progress,
  });

  /// 核心 API：`fetch(url, init?)`。
  Future<FetchResponse> fetch({required String url, FetchInit? init});

  factory HttpClient() => RustLib.instance.api.crateApiHttpHttpClientNew();
}

/// 单次 `fetch` 的 init（对齐 Fetch API 的 RequestInit）。
class FetchInit {
  final String? method;
  final Map<String, String>? headers;
  final Map<String, String>? query;
  final Uint8List? body;
  final BigInt? timeoutMs;
  final bool? followRedirects;

  const FetchInit({
    this.method,
    this.headers,
    this.query,
    this.body,
    this.timeoutMs,
    this.followRedirects,
  });

  static Future<FetchInit> default_() =>
      RustLib.instance.api.crateApiHttpFetchInitDefault();

  @override
  int get hashCode =>
      method.hashCode ^
      headers.hashCode ^
      query.hashCode ^
      body.hashCode ^
      timeoutMs.hashCode ^
      followRedirects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FetchInit &&
          runtimeType == other.runtimeType &&
          method == other.method &&
          headers == other.headers &&
          query == other.query &&
          body == other.body &&
          timeoutMs == other.timeoutMs &&
          followRedirects == other.followRedirects;
}

/// Fetch 响应。
class FetchResponse {
  final int status;
  final String statusText;
  final bool ok;
  final Map<String, String> headers;
  final Uint8List body;
  final String url;
  final bool redirected;

  const FetchResponse({
    required this.status,
    required this.statusText,
    required this.ok,
    required this.headers,
    required this.body,
    required this.url,
    required this.redirected,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      statusText.hashCode ^
      ok.hashCode ^
      headers.hashCode ^
      body.hashCode ^
      url.hashCode ^
      redirected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FetchResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          statusText == other.statusText &&
          ok == other.ok &&
          headers == other.headers &&
          body == other.body &&
          url == other.url &&
          redirected == other.redirected;
}

/// 客户端级默认配置。
class HttpClientOptions {
  final String? baseUrl;
  final Map<String, String>? defaultHeaders;

  /// 整请求超时（毫秒），默认 30000。
  final BigInt? timeoutMs;

  /// 连接超时（毫秒），默认 15000。
  final BigInt? connectTimeoutMs;

  /// 是否跟随重定向，默认 true。
  final bool? followRedirects;

  /// 强制直连、忽略代理。
  final bool? noProxy;

  /// 覆盖本次客户端使用的 HTTP 代理（例如 `http://127.0.0.1:7890`）。
  /// 设置后优先于全局代理配置。
  final String? httpProxy;

  /// 覆盖全局 TLS 校验；`None` 时跟随全局配置。
  final bool? dangerAcceptInvalidCerts;
  final String? userAgent;

  const HttpClientOptions({
    this.baseUrl,
    this.defaultHeaders,
    this.timeoutMs,
    this.connectTimeoutMs,
    this.followRedirects,
    this.noProxy,
    this.httpProxy,
    this.dangerAcceptInvalidCerts,
    this.userAgent,
  });

  static Future<HttpClientOptions> default_() =>
      RustLib.instance.api.crateApiHttpHttpClientOptionsDefault();

  @override
  int get hashCode =>
      baseUrl.hashCode ^
      defaultHeaders.hashCode ^
      timeoutMs.hashCode ^
      connectTimeoutMs.hashCode ^
      followRedirects.hashCode ^
      noProxy.hashCode ^
      httpProxy.hashCode ^
      dangerAcceptInvalidCerts.hashCode ^
      userAgent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpClientOptions &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          defaultHeaders == other.defaultHeaders &&
          timeoutMs == other.timeoutMs &&
          connectTimeoutMs == other.connectTimeoutMs &&
          followRedirects == other.followRedirects &&
          noProxy == other.noProxy &&
          httpProxy == other.httpProxy &&
          dangerAcceptInvalidCerts == other.dangerAcceptInvalidCerts &&
          userAgent == other.userAgent;
}

/// 下载进度事件。
class HttpProgress {
  final BigInt received;
  final BigInt? total;

  const HttpProgress({required this.received, this.total});

  @override
  int get hashCode => received.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpProgress &&
          runtimeType == other.runtimeType &&
          received == other.received &&
          total == other.total;
}
