// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `load_image`

/// 将任意支持的图片格式转换为 WebP，并覆盖写入原路径。
///
/// [input_path] 待转换图片的本地绝对路径。
/// [image_type] 图片类型提示，例如 `png`、`jpg`、`jpeg`、`webp`、`gif`、`bmp`。
///             传入空字符串或不支持的值时会根据文件头自动识别。
///             固定使用 95.0 质量，兼顾画质与压缩率。
Future<void> convertImageToWebp({
  required String inputPath,
  required String imageType,
}) => RustLib.instance.api.crateApiImageConvertImageToWebp(
  inputPath: inputPath,
  imageType: imageType,
);

/// 将图片转换为 PNG。
///
/// 格式校验（仅支持 jpg/png/非动图 webp）请在 Dart 侧完成，本函数只负责解码并输出 PNG。
/// 转换后的 PNG 写入 [output_path]。
Future<void> convertImageToPng({
  required String inputPath,
  required String outputPath,
}) => RustLib.instance.api.crateApiImageConvertImageToPng(
  inputPath: inputPath,
  outputPath: outputPath,
);
