// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `call_bundle_once_inner`, `call_current_bundle_inner`, `call_loaded_bundle_inner`, `clear_runtime_call_tasks`, `create_qjs_runtime`, `current_bundle_name`, `ensure_jm_http_loaded`, `insert_qjs_call_task`, `load_bundle_inner`, `parse_args_array`, `parse_ok_json_payload`, `qjs_call_start_inner`, `qjs_call_task_map`, `qjs_runtime_if_exists`, `qjs_runtime_map`, `qjs_runtime`, `replace_bundle_inner`, `take_qjs_call_task`

Future<void> qjsReplaceBundle({
  required String runtimeName,
  required String bundleName,
  required String bundleJs,
}) => RustLib.instance.api.crateApiJsQjsReplaceBundle(
  runtimeName: runtimeName,
  bundleName: bundleName,
  bundleJs: bundleJs,
);

Future<String> qjsCall({
  required String runtimeName,
  required String fnPath,
  required String argsJson,
}) => RustLib.instance.api.crateApiJsQjsCall(
  runtimeName: runtimeName,
  fnPath: fnPath,
  argsJson: argsJson,
);

Future<BigInt> qjsCallStart({
  required String runtimeName,
  required String fnPath,
  required String argsJson,
}) => RustLib.instance.api.crateApiJsQjsCallStart(
  runtimeName: runtimeName,
  fnPath: fnPath,
  argsJson: argsJson,
);

Future<String> qjsCallWait({
  required String runtimeName,
  required BigInt taskId,
}) => RustLib.instance.api.crateApiJsQjsCallWait(
  runtimeName: runtimeName,
  taskId: taskId,
);

Future<bool> qjsCallCancel({
  required String runtimeName,
  required BigInt taskId,
}) => RustLib.instance.api.crateApiJsQjsCallCancel(
  runtimeName: runtimeName,
  taskId: taskId,
);

Future<String> qjsCallOnce({
  required String runtimeName,
  required String bundleJs,
  required String fnPath,
  required String argsJson,
}) => RustLib.instance.api.crateApiJsQjsCallOnce(
  runtimeName: runtimeName,
  bundleJs: bundleJs,
  fnPath: fnPath,
  argsJson: argsJson,
);

Future<bool> qjsClearBundle({required String runtimeName}) =>
    RustLib.instance.api.crateApiJsQjsClearBundle(runtimeName: runtimeName);

Future<String> qjsCurrentBundle({required String runtimeName}) =>
    RustLib.instance.api.crateApiJsQjsCurrentBundle(runtimeName: runtimeName);

Future<bool> qjsDropRuntime({required String runtimeName}) =>
    RustLib.instance.api.crateApiJsQjsDropRuntime(runtimeName: runtimeName);

Future<String> jmRequest({required String payloadJson}) =>
    RustLib.instance.api.crateApiJsJmRequest(payloadJson: payloadJson);

Future<String> testHelloWorld() =>
    RustLib.instance.api.crateApiJsTestHelloWorld();
