// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `canonicalize_iana_id`, `format_offset_seconds`, `normalize_locale`

/// 获取系统首选语言，返回统一的 BCP-47 字符串（等价于 Web 的 `navigator.language`）。
/// Get the system's most preferred language as a unified BCP-47 string.
/// Equivalent to `navigator.language` on the web.
///
/// 先用 ICU4X 做规范化和常见别名处理，再按本项目惯例对中文做简化：
/// - `zh-Hans-CN` / `zh-Hans` / `zh-CN` / `zh` → `zh-CN`
/// - `zh-Hant-TW` / `zh-Hant` / `zh-TW` → `zh-TW`
/// - `zh-Hant-HK` / `zh-HK` → `zh-HK`
///
/// 其他 locale 按 ICU4X 规范化输出，如 `en-US`、`de-DE`、`ja-JP`。
String getSystemLanguage() =>
    RustLib.instance.api.crateApiLocalizationGetSystemLanguage();

/// 获取系统按优先级排序的语言列表（等价于 Web 的 `navigator.languages`）。
/// Get the system's preferred languages in descending order of preference.
/// Equivalent to `navigator.languages` on the web.
List<String> getSystemLanguages() =>
    RustLib.instance.api.crateApiLocalizationGetSystemLanguages();

/// 将任意 locale 字符串规范化为统一的 BCP-47 格式。
/// Normalize an arbitrary locale string to a unified BCP-47 format.
///
/// 先用 ICU4X 做规范化和常见别名处理，再按本项目惯例对中文做简化：
/// - `zh-Hans-CN` / `zh-Hans` / `zh-CN` / `zh` → `zh-CN`
/// - `zh-Hant-TW` / `zh-Hant` / `zh-TW` → `zh-TW`
/// - `zh-Hant-HK` / `zh-HK` → `zh-HK`
///
/// 其他 locale 按 ICU4X 规范化输出，如 `en-US`、`de-DE`、`ja-JP`。
String formatLocaleBcp47({required String locale}) =>
    RustLib.instance.api.crateApiLocalizationFormatLocaleBcp47(locale: locale);

/// 获取系统时区 IANA 名称，如 `Asia/Shanghai`。
/// Get the system timezone IANA name, e.g. `Asia/Shanghai`.
String getSystemTimezone() =>
    RustLib.instance.api.crateApiLocalizationGetSystemTimezone();

/// 获取系统时区相对于 UTC 的偏移，格式为 `+HH:MM` / `-HH:MM`。
/// Get the system timezone offset from UTC as `+HH:MM` / `-HH:MM`.
String getSystemTimezoneOffset() =>
    RustLib.instance.api.crateApiLocalizationGetSystemTimezoneOffset();
