// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BoxedFormatter`, `LogHttpWriter`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `drop`, `flush`, `fmt`, `format_event`, `make_writer_for`, `make_writer`, `write`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LogHttpMakeWriter>>
abstract class LogHttpMakeWriter implements RustOpaqueInterface {
  static Future<LogHttpMakeWriter> default_() =>
      RustLib.instance.api.crateApiLoggerLogHttpMakeWriterDefault();
}
