// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 获取 Rust 端内存使用情况
Future<RustMemoryInfo> getRustMemoryInfo() =>
    RustLib.instance.api.crateApiMemoryGetRustMemoryInfo();

/// 重置 Rust 内存统计
Future<void> resetRustMemoryStats() =>
    RustLib.instance.api.crateApiMemoryResetRustMemoryStats();

/// 获取 Rust 内存使用的格式化字符串
Future<String> getRustMemorySummary() =>
    RustLib.instance.api.crateApiMemoryGetRustMemorySummary();

class RustMemoryInfo {
  final BigInt totalAllocated;
  final BigInt peakAllocated;
  final BigInt allocationCount;
  final BigInt deallocationCount;
  final List<TaggedAllocation> taggedAllocations;

  const RustMemoryInfo({
    required this.totalAllocated,
    required this.peakAllocated,
    required this.allocationCount,
    required this.deallocationCount,
    required this.taggedAllocations,
  });

  @override
  int get hashCode =>
      totalAllocated.hashCode ^
      peakAllocated.hashCode ^
      allocationCount.hashCode ^
      deallocationCount.hashCode ^
      taggedAllocations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustMemoryInfo &&
          runtimeType == other.runtimeType &&
          totalAllocated == other.totalAllocated &&
          peakAllocated == other.peakAllocated &&
          allocationCount == other.allocationCount &&
          deallocationCount == other.deallocationCount &&
          taggedAllocations == other.taggedAllocations;
}

class TaggedAllocation {
  final String tag;
  final BigInt size;

  const TaggedAllocation({required this.tag, required this.size});

  @override
  int get hashCode => tag.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaggedAllocation &&
          runtimeType == other.runtimeType &&
          tag == other.tag &&
          size == other.size;
}
