// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../qjs.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `leak_vec_to_qjs_task_bytes`

Future<void> qjsReplaceBundle({
  required String runtimeName,
  required String bundleName,
  required String bundleJs,
}) => RustLib.instance.api.crateApiQjsQjsReplaceBundle(
  runtimeName: runtimeName,
  bundleName: bundleName,
  bundleJs: bundleJs,
);

/// 统一执行入口:调用插件 bundle 里的函数,返回原始字节。
///
/// `is_once=true` 用 `bundle_js`/`bundle_url` 走一次性 debug 池(不常驻);
/// `false` 走常驻运行时里已加载的当前 bundle。
/// 返回值为 Rust 堆缓冲句柄:JS 返回 `Uint8Array`/`ArrayBuffer` 时为真实字节,
/// 否则为 JSON 序列化后的 UTF-8 字节,由调用方自行转换。
/// 缓冲所有权已移交给 Dart,用完后必须调用 `qjs_free_task_bytes` 释放。
Future<QjsTaskBytes> qjsTaskCall({
  required String runtimeName,
  required String taskGroupKey,
  required bool isOnce,
  String? bundleJs,
  String? bundleUrl,
  required String fnPath,
  required String argsJson,
}) => RustLib.instance.api.crateApiQjsQjsTaskCall(
  runtimeName: runtimeName,
  taskGroupKey: taskGroupKey,
  isOnce: isOnce,
  bundleJs: bundleJs,
  bundleUrl: bundleUrl,
  fnPath: fnPath,
  argsJson: argsJson,
);

/// 释放 [`qjs_task_call`] 返回的 Rust 堆缓冲（把所有权归还给 Rust）。
///
/// 同一 `(ptr, len)` 只能释放一次；重复释放或释放非法句柄是未定义行为。
void qjsFreeTaskBytes({required BigInt ptr, required BigInt len}) =>
    RustLib.instance.api.crateApiQjsQjsFreeTaskBytes(ptr: ptr, len: len);

Future<bool> qjsClearBundle({required String runtimeName}) =>
    RustLib.instance.api.crateApiQjsQjsClearBundle(runtimeName: runtimeName);

Future<String> qjsCurrentBundle({required String runtimeName}) =>
    RustLib.instance.api.crateApiQjsQjsCurrentBundle(runtimeName: runtimeName);

Future<bool> qjsDropRuntime({required String runtimeName}) =>
    RustLib.instance.api.crateApiQjsQjsDropRuntime(runtimeName: runtimeName);

Future<QjsCancelTasksByGroupResult> qjsCancelTasksByGroup({
  required String runtimeName,
  required String taskGroupKey,
}) => RustLib.instance.api.crateApiQjsQjsCancelTasksByGroup(
  runtimeName: runtimeName,
  taskGroupKey: taskGroupKey,
);

Future<String> qjsDebugSnapshot({required String runtimeName}) =>
    RustLib.instance.api.crateApiQjsQjsDebugSnapshot(runtimeName: runtimeName);

void setHttpProxy({required String proxy}) =>
    RustLib.instance.api.crateApiQjsSetHttpProxy(proxy: proxy);

void setSocks5Proxy({required String proxy}) =>
    RustLib.instance.api.crateApiQjsSetSocks5Proxy(proxy: proxy);

void setTlsVerifyEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiQjsSetTlsVerifyEnabled(enabled: enabled);

/// 设置 QuickJS 运行时错误消息语言（BCP-47 locale），默认 zh-CN
/// Set the QuickJS runtime error-message language (BCP-47 locale), defaults to zh-CN.
void setQjsErrorMessageLanguage({required String lang}) =>
    RustLib.instance.api.crateApiQjsSetQjsErrorMessageLanguage(lang: lang);

bool isTlsVerifyEnabled() =>
    RustLib.instance.api.crateApiQjsIsTlsVerifyEnabled();

void setQjsErrorStackEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiQjsSetQjsErrorStackEnabled(enabled: enabled);

void configureBridgeRuntime({
  required List<String> allowedRoutePrefixes,
  required BigInt maxArgsJsonBytes,
  required BigInt maxReturnBinaryBytes,
}) => RustLib.instance.api.crateApiQjsConfigureBridgeRuntime(
  allowedRoutePrefixes: allowedRoutePrefixes,
  maxArgsJsonBytes: maxArgsJsonBytes,
  maxReturnBinaryBytes: maxReturnBinaryBytes,
);

void setHostCacheGcEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiQjsSetHostCacheGcEnabled(enabled: enabled);

bool isHostCacheGcEnabled() =>
    RustLib.instance.api.crateApiQjsIsHostCacheGcEnabled();

void setLogHttpForward({required String url}) =>
    RustLib.instance.api.crateApiQjsSetLogHttpForward(url: url);

String getJsBundle({required String name}) =>
    RustLib.instance.api.crateApiQjsGetJsBundle(name: name);

Future<bool> isQjsRuntimeInitialized({required String name}) =>
    RustLib.instance.api.crateApiQjsIsQjsRuntimeInitialized(name: name);

Future<void> buildQjsRuntime({required QjsRuntimeBuildRequest request}) =>
    RustLib.instance.api.crateApiQjsBuildQjsRuntime(request: request);

void registerFunction({
  required String functionName,
  required FutureOr<String> Function(String) dartCallback,
}) => RustLib.instance.api.crateApiQjsRegisterFunction(
  functionName: functionName,
  dartCallback: dartCallback,
);

void initRustFunctions() => RustLib.instance.api.crateApiQjsInitRustFunctions();

String openccConvert({required String text, required String config}) =>
    RustLib.instance.api.crateApiQjsOpenccConvert(text: text, config: config);

/// Rust 堆缓冲句柄，所有权已移交给 Dart。
///
/// `ptr` 指向 heap 上一段 `len` 字节的连续内存（Rust `Vec<u8>` 的 data 指针）。
/// Dart 侧应把它当作零拷贝的 `Uint8List` 视图使用（`Uint8List.view`），
/// 用完后调用 [`qjs_free_task_bytes`] 释放，或经 Dart 侧 finalizer 自动释放。
/// `ptr == 0 && len == 0` 表示空结果。
class QjsTaskBytes {
  final BigInt ptr;
  final BigInt len;

  const QjsTaskBytes({required this.ptr, required this.len});

  @override
  int get hashCode => ptr.hashCode ^ len.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QjsTaskBytes &&
          runtimeType == other.runtimeType &&
          ptr == other.ptr &&
          len == other.len;
}
