// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../qjs.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> qjsReplaceBundle({
  required String runtimeName,
  required String bundleName,
  required String bundleJs,
}) => RustLib.instance.api.crateApiQjsQjsReplaceBundle(
  runtimeName: runtimeName,
  bundleName: bundleName,
  bundleJs: bundleJs,
);

Future<String> qjsCall({
  required String runtimeName,
  required String fnPath,
  required String argsJson,
}) => RustLib.instance.api.crateApiQjsQjsCall(
  runtimeName: runtimeName,
  fnPath: fnPath,
  argsJson: argsJson,
);

Future<BigInt> qjsCallTaskStart({
  required String runtimeName,
  required String taskGroupKey,
  required String fnPath,
  required String argsJson,
}) => RustLib.instance.api.crateApiQjsQjsCallTaskStart(
  runtimeName: runtimeName,
  taskGroupKey: taskGroupKey,
  fnPath: fnPath,
  argsJson: argsJson,
);

Future<String> qjsCallTaskWait({
  required String runtimeName,
  required BigInt taskId,
}) => RustLib.instance.api.crateApiQjsQjsCallTaskWait(
  runtimeName: runtimeName,
  taskId: taskId,
);

Future<String> qjsCallOnce({
  required String runtimeName,
  required String bundleJs,
  required String fnPath,
  required String argsJson,
}) => RustLib.instance.api.crateApiQjsQjsCallOnce(
  runtimeName: runtimeName,
  bundleJs: bundleJs,
  fnPath: fnPath,
  argsJson: argsJson,
);

Future<BigInt> qjsCallOnceTaskStart({
  required String runtimeName,
  required String bundleJs,
  required String fnPath,
  required String argsJson,
  required String taskGroupKey,
}) => RustLib.instance.api.crateApiQjsQjsCallOnceTaskStart(
  runtimeName: runtimeName,
  bundleJs: bundleJs,
  fnPath: fnPath,
  argsJson: argsJson,
  taskGroupKey: taskGroupKey,
);

Future<String> qjsCallOnceTaskWait({
  required String runtimeName,
  required BigInt taskId,
}) => RustLib.instance.api.crateApiQjsQjsCallOnceTaskWait(
  runtimeName: runtimeName,
  taskId: taskId,
);

Future<bool> qjsClearBundle({required String runtimeName}) =>
    RustLib.instance.api.crateApiQjsQjsClearBundle(runtimeName: runtimeName);

Future<String> qjsCurrentBundle({required String runtimeName}) =>
    RustLib.instance.api.crateApiQjsQjsCurrentBundle(runtimeName: runtimeName);

Future<bool> qjsDropRuntime({required String runtimeName}) =>
    RustLib.instance.api.crateApiQjsQjsDropRuntime(runtimeName: runtimeName);

Future<QjsCancelTaskResult> qjsCancelTask({
  required String runtimeName,
  required BigInt taskId,
}) => RustLib.instance.api.crateApiQjsQjsCancelTask(
  runtimeName: runtimeName,
  taskId: taskId,
);

Future<QjsCancelTasksByGroupResult> qjsCancelTasksByGroup({
  required String runtimeName,
  required String taskGroupKey,
}) => RustLib.instance.api.crateApiQjsQjsCancelTasksByGroup(
  runtimeName: runtimeName,
  taskGroupKey: taskGroupKey,
);

Future<Uint8List> qjsFetchImageBytes({
  required String runtimeName,
  required String fnPath,
  required String argsJson,
}) => RustLib.instance.api.crateApiQjsQjsFetchImageBytes(
  runtimeName: runtimeName,
  fnPath: fnPath,
  argsJson: argsJson,
);

Future<BigInt> qjsFetchImageBytesTaskStart({
  required String runtimeName,
  required String taskGroupKey,
  required String fnPath,
  required String argsJson,
}) => RustLib.instance.api.crateApiQjsQjsFetchImageBytesTaskStart(
  runtimeName: runtimeName,
  taskGroupKey: taskGroupKey,
  fnPath: fnPath,
  argsJson: argsJson,
);

Future<Uint8List> qjsFetchImageBytesTaskWait({
  required String runtimeName,
  required BigInt taskId,
}) => RustLib.instance.api.crateApiQjsQjsFetchImageBytesTaskWait(
  runtimeName: runtimeName,
  taskId: taskId,
);

Future<Uint8List> qjsFetchImageBytesOnce({
  required String runtimeName,
  required String bundleJs,
  required String fnPath,
  required String argsJson,
}) => RustLib.instance.api.crateApiQjsQjsFetchImageBytesOnce(
  runtimeName: runtimeName,
  bundleJs: bundleJs,
  fnPath: fnPath,
  argsJson: argsJson,
);

Future<BigInt> qjsFetchImageBytesOnceTaskStart({
  required String runtimeName,
  required String bundleJs,
  required String fnPath,
  required String argsJson,
  required String taskGroupKey,
}) => RustLib.instance.api.crateApiQjsQjsFetchImageBytesOnceTaskStart(
  runtimeName: runtimeName,
  bundleJs: bundleJs,
  fnPath: fnPath,
  argsJson: argsJson,
  taskGroupKey: taskGroupKey,
);

Future<Uint8List> qjsFetchImageBytesOnceTaskWait({
  required String runtimeName,
  required BigInt taskId,
}) => RustLib.instance.api.crateApiQjsQjsFetchImageBytesOnceTaskWait(
  runtimeName: runtimeName,
  taskId: taskId,
);

Future<void> setHttpProxy({required String proxy}) =>
    RustLib.instance.api.crateApiQjsSetHttpProxy(proxy: proxy);

Future<void> setSocks5Proxy({required String proxy}) =>
    RustLib.instance.api.crateApiQjsSetSocks5Proxy(proxy: proxy);

void setQjsErrorStackEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiQjsSetQjsErrorStackEnabled(enabled: enabled);

void setHostCacheGcEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiQjsSetHostCacheGcEnabled(enabled: enabled);

bool isHostCacheGcEnabled() =>
    RustLib.instance.api.crateApiQjsIsHostCacheGcEnabled();

Future<void> registerLoadPluginConfig({
  required FutureOr<String> Function(String, String, String) dartCallback,
}) => RustLib.instance.api.crateApiQjsRegisterLoadPluginConfig(
  dartCallback: dartCallback,
);

Future<void> registerSavePluginConfig({
  required FutureOr<String> Function(String, String, String) dartCallback,
}) => RustLib.instance.api.crateApiQjsRegisterSavePluginConfig(
  dartCallback: dartCallback,
);

void setLogHttpForward({required String url}) =>
    RustLib.instance.api.crateApiQjsSetLogHttpForward(url: url);

String getJsBundle({required String name}) =>
    RustLib.instance.api.crateApiQjsGetJsBundle(name: name);

Future<bool> isQjsRuntimeInitialized({required String name}) =>
    RustLib.instance.api.crateApiQjsIsQjsRuntimeInitialized(name: name);

Future<void> buildQjsRuntime({required QjsRuntimeBuildRequest request}) =>
    RustLib.instance.api.crateApiQjsBuildQjsRuntime(request: request);

void registerFunction({
  required String functionName,
  required FutureOr<String> Function(String) dartCallback,
}) => RustLib.instance.api.crateApiQjsRegisterFunction(
  functionName: functionName,
  dartCallback: dartCallback,
);

void initRustFunctions() => RustLib.instance.api.crateApiQjsInitRustFunctions();

String openccConvert({required String text, required String config}) =>
    RustLib.instance.api.crateApiQjsOpenccConvert(text: text, config: config);
