// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../compressed/compressed.dart';
import '../decode/decode.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<String> sleepTest() => RustLib.instance.api.crateApiSimpleSleepTest();

Future<void> antiObfuscationPicture({required ImageInfo imageInfo}) => RustLib
    .instance
    .api
    .crateApiSimpleAntiObfuscationPicture(imageInfo: imageInfo);

Future<String> compressImage({required List<int> imageBytes}) =>
    RustLib.instance.api.crateApiSimpleCompressImage(imageBytes: imageBytes);

Future<String> asyncHttpGet({required String url}) =>
    RustLib.instance.api.crateApiSimpleAsyncHttpGet(url: url);

Future<void> packFolder({
  required String destPath,
  required PackInfo packInfo,
}) => RustLib.instance.api.crateApiSimplePackFolder(
  destPath: destPath,
  packInfo: packInfo,
);

Stream<String> streamTest() => RustLib.instance.api.crateApiSimpleStreamTest();
