// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 启动一个命名管道监听器，等待外部进程（如安装器）发送关闭信号。
/// 当收到信号时，通过 StreamSink 向 Dart 侧发送 `true`。
/// 仅在 Windows 上有效，其他平台不做任何操作。
Stream<bool> startShutdownListener() =>
    RustLib.instance.api.crateApiSystemStartShutdownListener();
