// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_client`, `directory_request_path`, `download_file_with_retry`, `ensure_directory`, `is_directory_entry`, `normalize_any_managed_path`, `normalize_managed_href`, `normalize_remote_path`, `path_depth`, `strip_to_managed_root`, `upload_bytes`

Future<void> webdavTestConnection({
  required String host,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiWebdavWebdavTestConnection(
  host: host,
  username: username,
  password: password,
);

Future<void> webdavEnsureRemoteReady({
  required String host,
  required String username,
  required String password,
  required String syncRootName,
}) => RustLib.instance.api.crateApiWebdavWebdavEnsureRemoteReady(
  host: host,
  username: username,
  password: password,
  syncRootName: syncRootName,
);

Future<String> webdavDownloadText({
  required String host,
  required String username,
  required String password,
  required String syncRootName,
  required String legacyDataRootName,
  required String legacySettingsRootName,
  required String remotePath,
}) => RustLib.instance.api.crateApiWebdavWebdavDownloadText(
  host: host,
  username: username,
  password: password,
  syncRootName: syncRootName,
  legacyDataRootName: legacyDataRootName,
  legacySettingsRootName: legacySettingsRootName,
  remotePath: remotePath,
);

Future<void> webdavUploadText({
  required String host,
  required String username,
  required String password,
  required String syncRootName,
  required String legacyDataRootName,
  required String legacySettingsRootName,
  required String remotePath,
  required String value,
}) => RustLib.instance.api.crateApiWebdavWebdavUploadText(
  host: host,
  username: username,
  password: password,
  syncRootName: syncRootName,
  legacyDataRootName: legacyDataRootName,
  legacySettingsRootName: legacySettingsRootName,
  remotePath: remotePath,
  value: value,
);

Future<List<String>> webdavListRemoteDataFiles({
  required String host,
  required String username,
  required String password,
  required String syncRootName,
  required String legacyDataRootName,
  required String legacySettingsRootName,
}) => RustLib.instance.api.crateApiWebdavWebdavListRemoteDataFiles(
  host: host,
  username: username,
  password: password,
  syncRootName: syncRootName,
  legacyDataRootName: legacyDataRootName,
  legacySettingsRootName: legacySettingsRootName,
);

Future<Uint8List> webdavDownloadFile({
  required String host,
  required String username,
  required String password,
  required String syncRootName,
  required String legacyDataRootName,
  required String legacySettingsRootName,
  required String remotePath,
}) => RustLib.instance.api.crateApiWebdavWebdavDownloadFile(
  host: host,
  username: username,
  password: password,
  syncRootName: syncRootName,
  legacyDataRootName: legacyDataRootName,
  legacySettingsRootName: legacySettingsRootName,
  remotePath: remotePath,
);

Future<void> webdavUploadBytes({
  required String host,
  required String username,
  required String password,
  required String syncRootName,
  required String legacyDataRootName,
  required String legacySettingsRootName,
  required String remotePath,
  required List<int> data,
  required String contentType,
}) => RustLib.instance.api.crateApiWebdavWebdavUploadBytes(
  host: host,
  username: username,
  password: password,
  syncRootName: syncRootName,
  legacyDataRootName: legacyDataRootName,
  legacySettingsRootName: legacySettingsRootName,
  remotePath: remotePath,
  data: data,
  contentType: contentType,
);

Future<void> webdavDeleteRemoteFiles({
  required String host,
  required String username,
  required String password,
  required List<String> remotePaths,
  required String syncRootName,
  required String legacyDataRootName,
  required String legacySettingsRootName,
}) => RustLib.instance.api.crateApiWebdavWebdavDeleteRemoteFiles(
  host: host,
  username: username,
  password: password,
  remotePaths: remotePaths,
  syncRootName: syncRootName,
  legacyDataRootName: legacyDataRootName,
  legacySettingsRootName: legacySettingsRootName,
);
